baseURL = 'https://monotone.studio/docs/'
languageCode = 'en-us'
title = 'monotone'
theme = 'hugo-book'

[params]
  BookSection = '/'
  BookSearch = false
  BookRepo = 'https://github.com/monotone-studio/monotone-docs'
  BookEditPath = 'edit/main'
