baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'monotone'
theme = 'hugo-book'

[params]
  BookSearch = false

  ## Set source repository location.
  ## Used for 'Last Modified' and 'Edit this page' links.
  #BookRepo = 'https://github.com/alex-shpak/hugo-book'

  ## Enable "Edit this page" links for 'doc' page type.
  ## Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  ## Edit path must point to root directory of repo.
  #BookEditPath = 'edit/main/exampleSite'
